name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install nbconvert jupyter

      - name: Convert notebooks to HTML
        run: |
          mkdir -p website/_notebooks
          jupyter nbconvert notebooks/*.ipynb --to html --output-dir=website/_notebooks

      - name: Save build artifact for manual inspection
        uses: actions/upload-artifact@v4
        with:
          name: site-preview
          path: website

      - name: Upload site artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: website

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4